name: build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  dockerize:
    runs-on: ubuntu-latest
    steps:
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      -
        name: Build and push images
        id: docker_build
        uses: docker/build-push-action@v2.4.0
        with:
          push: true
          tags: rifqisah/rifqisah:latest
      -
        name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}

  deploy:
    needs: [dockerize]
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, '[skip deploy]')"
    steps:
      -
        name: Creating proxy
        uses: twingate/github-action@v1
        with:
          service-key: ${{ secrets.TWINGATE_KEY }}
      -
        name: Connecting to server & Start deploy
        uses: appleboy/ssh-action@v0.1.4
        with:
          host: ${{secrets.SSH_HOST}}
          port: ${{ secrets.SSH_PORT}}
          username: ${{ secrets.SSH_USERNAME }}
          password: ${{ secrets.SSH_PASSWORD }}
          script: |
            cd apps/projects/rifqisah
            docker compose down web
            docker compose pull web
            docker compose up -d web